# Generated by Django 3.2.7 on 2021-09-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='area_name',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='capital_name',
            new_name='capital',
        ),
    ]
